### ISSUE TITLE
Error: redirect_uri_mismatch

### ISSUE THREAD

**Issue by joshgowans** [greenleafadvancement/org.civicrm.googlegroups#1]
Following the instructions as well as includin a redirect URL in the oauth settings results in a Eror: redirect_uri_mismatch

>The redirect URI in the request, https://runningindustry.org/civicrm/googlegroups/settings?reset=1, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/826356467579-ofj292snvjrd1b59k4as3hq13r3cd18q.apps.googleusercontent.com?project=826356467579

Request details:

> response_type=code
access_type=offline
client_id=826356467579-ofj292snvjrd1b59k4as3hq13r3cd18q.apps.googleusercontent.com
redirect_uri=https://runningindustry.org/civicrm/googlegroups/settings?reset=1
state=
scope=https://www.googleapis.com/auth/admin.directory.group
approval_prompt=auto

**Comment by deepak-srivastava** [comment]
@joshgowans 

**1. Make sure Authorized redirect URI is set in Oauth Console.**

![image](https://user-images.githubusercontent.com/3448551/67213341-ca7a1600-f415-11e9-8c7d-61e5444c3718.png)

**2. Also make sure domain is listed in Authorized domains list, in the client credentials screen (where we generate client id and secret).**

![image](https://user-images.githubusercontent.com/3448551/67213491-01e8c280-f416-11e9-8232-7734ff99b851.png)

**Comment by deepak-srivastava** [comment]
Think this one is resolved.
