### ISSUE TITLE
Missing Google Group dropdown

### ISSUE THREAD

**Issue by jonathandhn** [greenleafadvancement/org.civicrm.googlegroups#10]
CiviCRM 5.30.1 Drupal 7
Oauth token well set-up, but the dropdown is missing on each groups edit panel. 
Can't use the app so...

**Comment by mmellace** [comment]
I had the same problem. Check your drupal logs and go the the url that it tells you to go to in order to enable the API.   https://console.developers.google.com/apis/api/admin.googleapis.com/overview?project=

this is the error message that i saw on my end that led me to the fix:

$civicrm_api3_googlegroups_getgroups exception $errors = Array ( [0] => Array ( [message] => Admin SDK API has not been used in project 4163746709 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/admin.googleapis.com/overview?project=4163746709 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. [domain] => usageLimits [reason] => accessNotConfigured [extendedHelp] => https://console.developers.google.com ) )

**Comment by deepak-srivastava** [comment]
Please try latest release (2.4 at this point), and re-open if still an issue.

**Comment by andyburnsco** [comment]
Also seeing this now. Note, the latest ext 2.4 on CiviCRM 6.1.2 does not work. It results in this error with smarty. I did try and run civix on a fork https://github.com/andyburnsco/org.civicrm.googlegroups/tree/civix-upgrade and that resolves the error and install and setuyp suceeds, almost. See more below.

```
Error Details
=============
An error of type E_ERROR was caused in line 37 of the file /example/wp-content/plugins/civicrm/civicrm/packages/smarty5/Smarty.php. Error message: Uncaught Error: Cannot access protected property Smarty\Smarty::$template_dir in /example/wp-content/plugins/civicrm/civicrm/packages/smarty5/Smarty.php:37
Stack trace:
#0 /example/wp-content/uploads/civicrm/ext/org.civicrm.googlegroups/googlegroups.civix.php(99): Smarty->__get()
#1 /example/wp-content/uploads/civicrm/ext/org.civicrm.googlegroups/googlegroups.php(13): _googlegroups_civix_civicrm_config()
#2 /example/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php(276): googlegroups_civicrm_config()
#3 /example/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook/WordPress.php(135): CRM_Utils_Hook->runHooks()
#4 /example/wp-content/plugins/civicrm/civicrm/Civi/Core/CiviEventDispatcher.php(314): CRM_Utils_Hook_WordPress->invokeViaUF()
#5 /example/wp-content/plugins/civicrm/civicrm/vendor/symfony/event-dispatcher/EventDispatcher.php(230): Civi\Core\CiviEventDispatcher::delegateToUF()
#6 /example/wp-content/plugins/civicrm/civicrm/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
#7 /example/wp-content/plugins/civicrm/civicrm/Civi/Core/CiviEventDispatcher.php(263): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
#8 /example/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php(168): Civi\Core\CiviEventDispatcher->dispatch()
#9 /example/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php(1490): CRM_Utils_Hook->invoke()
#10 /example/wp-content/plugins/civicrm/civicrm/CRM/Core/Config.php(100): CRM_Utils_Hook::config()
#11 /example/wp-content/plugins/civicrm/includes/civicrm.admin.php(444): CRM_Core_Config::singleton()
#12 /example/wp-content/plugins/civicrm/civicrm.php(1044): CiviCRM_For_WordPress_Admin->initialize()
#13 /example/wp-content/plugins/civicrm-wp-profile-sync/includes/civicrm/cwps-civicrm.php(314): CiviCRM_For_WordPress->initialize()
#14 /example/wp-content/plugins/civicrm-wp-profile-sync/includes/acf/classes/cwps-acf-acf-field-type.php(121): CiviCRM_WP_Profile_Sync_CiviCRM->is_initialised()
#15 /example/wp-includes/class-wp-hook.php(324): CiviCRM_Profile_Sync_ACF_Field_Type->register_field_types()
#16 /example/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#17 /example/wp-includes/plugin.php(517): WP_Hook->do_action()
#18 /example/wp-content/plugins/advanced-custom-fields-pro/acf.php(351): do_action()
#19 /example/wp-includes/class-wp-hook.php(324): ACF->init()
#20 /example/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#21 /example/wp-includes/plugin.php(517): WP_Hook->do_action()
#22 /example/wp-settings.php(704): do_action()
#23 /example/wp-config.php(88): require_once('...')
#24 /example/wp-load.php(50): require_once('...')
#25 /example/wp-admin/admin.php(34): require_once('...')
#26 {main}
  thrown

```

Doing that, I can get the ext installed, setup and authorized (Access Token Refreshed) on the settings page. However, the group dropdown still does not work.

![Image](https://github.com/user-attachments/assets/f557fa75-f543-464b-86dc-965471380c9c)

@deepak-srivastava? Is this ext still in production on some sites?  Is there changes on google's end to need to add "scopes" for the Admin SDK API? Is this more than a civix regenerate issue?

**Comment by colemanw** [comment]
@deepak-srivastava I've changed the status of this extension on https://civicrm.org/extensions/google-groups-integration to "Unsupported" since it's not currently working.
