### ISSUE TITLE
Unable to reach the server. Please refresh this page in your browser and try again.

### ISSUE THREAD

**Issue by joshgowans** [greenleafadvancement/org.civicrm.googlegroups#2]
With extension enabled, running Drupal 7 and CiviCRM 5.17.4, when clicking on the settings of a group in the groups manager the settings popup fails to load and the screen displays error:

> Unable to reach the server. Please refresh this page in your browser and try again.

When the extension is disabled, the behavior returns to expected and the settings popup appears. However, the field for specifying the target Google Group remains in the settings UI:

![Manage Groups   The Running Industry Association (1)](https://user-images.githubusercontent.com/16521043/67140451-52172780-f252-11e9-98ee-09a14bfc3e5c.png)

**Comment by deepak-srivastava** [comment]
It appears like there is some problem with connection. Otherwise Google Group text box should appear like a dropdown.

May be try connecting again after resolving https://github.com/greenleafadvancement/org.civicrm.googlegroups/issues/1 and check?

**Comment by deepak-srivastava** [comment]
Based on last conversation on mattermost, i think this one is resolved. Please re-open if problem exists.
