### ISSUE TITLE
False positive sync

### ISSUE THREAD

**Issue by andyburnsco** [greenleafadvancement/org.civicrm.googlegroups#7]
Everything looks good and when I sync it looks successful. 

![1](https://user-images.githubusercontent.com/18341942/89346265-5f30c600-d66e-11ea-9517-14a495c9f2cf.png)

However, when I go to the Google Group, no members have changed. I have put the most lenient settings on the group e.g. 

![image](https://user-images.githubusercontent.com/18341942/89346152-327cae80-d66e-11ea-8bc6-00028474dd8d.png)

My authorized redirect URI's are:

- https://example.org/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fgooglegroups%2Fsettings&reset=1
- https://example.org

**Comment by andyburnsco** [comment]
Here is the error log:

**[info] $civicrm_api3_googlegroups_subscribe exception $e = Google_Service_Exception Object**
(
[errors:protected] =>
[message:protected] => Global HTTP Batch endpoint is deprecated. See https://g.co/cloud/global-batch-deprecation for info and migration steps.
[string:Exception:private] =>
[code:protected] => 404
[file:protected] => /var/.../wp-content/uploads/civicrm/ext/org.civicrm.googlegroups/vendor/google/apiclient/src/Google/Http/REST.php
[line:protected] => 118
[trace:Exception:private] => Array

...

I can paste the full error if you would like.

Also  **[info] $civicrm_api3_googlegroups_subscribe exception $errors is not set**

Talking with Google support, that means the type of requests sent by the this extension are deprecated as per the documentation: https://g.co/cloud/global-batch-deprecation

**Comment by guyiac** [comment]
@joshgowans or @deepak-srivastava  Do you have any input on this?

**Comment by deepak-srivastava** [comment]
@andyburnsco thanks for the heads-up. Full log would be even more helpful.

@guyiac @joshgowans 
It does sound like library is using some endpoint, support for which has stopped from Aug 12 2020.

It looks like "Google APIs Client Library for PHP" would need to be updated. I'm not sure at this point how much impact that would have on current implementation.
For less work/impact - we could upgrade it to the point where minimum requirements are met.

Just wondering if anyone else has started noticing the problem.

**Comment by deepak-srivastava** [comment]
@andyburnsco please try the latest release, and re-open if any issues.

**Comment by andyburnsco** [comment]
I have tried Master and it still says is a false positive.

The confirmation appears right as the google group did have 1 person in it.

![image](https://user-images.githubusercontent.com/18341942/92126956-6ca0b380-edc6-11ea-8c0f-d77593551be2.png)

But go to the google group and nothing changed.

![Untitled](https://user-images.githubusercontent.com/18341942/92127250-bbe6e400-edc6-11ea-8f7d-32003f8076e6.png)


I installed master, re-authorized (said it was already authorized) then flushed caches and synced.

**Comment by deepak-srivastava** [comment]
@andyburnsco try v2.1 release. And re-establish the connection from settings screen. And then try again.

**Comment by andyburnsco** [comment]
Ok, I tested the patches with master when I saw the notification this morning but will do 2.1 now too.

I did re-establish the connection. Do you want me remove it and re-connect? I'll need a reminder on how to remove.

**Comment by deepak-srivastava** [comment]
@andyburnsco To remove follow "Remove site or app access" section from https://support.google.com/accounts/answer/3466521?hl=en

**Comment by andyburnsco** [comment]
Working now. It needs to show _Access Token Refreshed_ on the settings page after re-authorizing.
